"""
Docstring for events

Voice Agent Event Types

This module defines typed dataclasses for all events that flow through the voice
agent pipeline, including STT events, TTS events, and ASR events.
"""


from typing import Any
import base64
import dataclasses
import time
from dataclasses import dataclass
from typing import Literal, Union

def _now_ms() -> int:
    "returns current unix timestamp in milliseconds"
    return int(time.time() * 1000)


@dataclass
class UserSpeechEvent:
    """Event representing user speech input"""
    audio_data: bytes # raw PCM audio data
    type: Literal['user_speech'] = 'user_speech'  
    timestamp: int = _now_ms()  # event timestamp in ms


@dataclass
class STTChunkEvent:
    """Event representing a partial STT transcription"""
    text: str  # partial transcription text
    type: Literal['stt_chunk'] = 'stt_chunk'
    is_final: bool = False  # whether this is a final chunk
    timestamp: int = _now_ms()  # event timestamp in ms


@dataclass
class STTOutputEvent:
    """Event representing a final STT transcription"""
    text: str  # final transcription text
    type: Literal['stt_output'] = 'stt_output'
    timestamp: int = _now_ms()  # event timestamp in ms


STTEvent = Union[STTChunkEvent, STTOutputEvent]

@dataclass
class AgentTriggerEvent:
    """Event indicating the agent has started its response generation"""
    text: str
    type: Literal['agent_trigger'] = 'agent_trigger'
    timestamp: int = _now_ms()  # event timestamp in ms

@dataclass
class AgentChunkEvent:
    """
    Event emitted during agent response generation for streaming text chunks.

    As the LLM generates its response, it streams tokens incrementally.
    These chunks enable real-time display of the agent's response and allow
    the TTS stage to begin synthesis before the complete response is generated,
    reducing overall latency.
    """

    text: str  # text chunk generated by the agent
    type: Literal['agent_chunk'] = 'agent_chunk'
    timestamp: int = _now_ms()  # event timestamp in ms


@dataclass
class AgentEndEvent:
    """Event indicating the agent has completed its response generation"""
    text: str  # optional final text (can be empty)
    type: Literal['agent_end'] = 'agent_end'
    timestamp: int = _now_ms()  # event timestamp in ms


@dataclass
class ToolCallEvent:
    """
    Event representing a tool call made by the agent.
    """
    id: str  # unique ID for the tool call
    tool_name: str  # name of the tool being called
    arguments: dict  # arguments passed to the tool
    type: Literal['tool_call'] = 'tool_call'
    timestamp: int = _now_ms()  # event timestamp in ms

@dataclass
class ToolReturnEvent:
    """
    Event representing the return value from a tool call.
    """

    id: str  # unique ID for the tool call
    tool_name: str  # name of the tool
    return_value: str  # return value from the tool
    type: Literal['tool_return'] = 'tool_return'
    timestamp: int = _now_ms()  # event timestamp in ms


# union of all agent events
AgentEvent = Union[AgentTriggerEvent, AgentChunkEvent, AgentEndEvent, ToolCallEvent, ToolReturnEvent]


@dataclass
class TTSChunkEvent:
    """Event representing a chunk of TTS audio data"""
    audio_data: bytes  # raw PCM audio data
    type: Literal['tts_chunk'] = 'tts_chunk'
    stream_sid: Any = None
    is_final: bool = False  # whether this is the final chunk
    timestamp: int = _now_ms()  # event timestamp in ms

@dataclass
class InterruptEvent:
    """Event representing an interrupt"""
    stream_sid: Any = None
    type: Literal['interrupt'] = 'interrupt'
    timestamp: int = _now_ms()  # event timestamp in ms


VoiceAgentEvent = Union[UserSpeechEvent, STTEvent, AgentEvent, TTSChunkEvent, InterruptEvent]

TwilioEvent = Union[TTSChunkEvent, InterruptEvent]

def event_to_dict(event: TwilioEvent) -> dict:
    """Convert a VoiceAgentEvent to a JSON-serializable dict"""
    if isinstance(event, TTSChunkEvent):
        return {
            "event": "media",
            "streamSid": event.stream_sid,
            "media": {
                "payload": base64.b64encode(event.audio_data).decode('utf-8')
            }
        }
    elif isinstance(event, InterruptEvent):
        return {
            "event": "clear",
            "streamSid": event.stream_sid
        }
    else:
        raise ValueError(f"Unknown event type: {type(event)}")